### ISSUE TITLE
missing d.month in positions_binning function ?

### ISSUE THREAD

**Issue by cezary69** [computationalprivacy/bandicoot#21]
in line 116 of helper/group
return (d.year, d.day, d.hour, d.minute // 30)

should't it be 
return (d.year, d.month, d.day, d.hour, d.minute // 30)

or I'm missing something ?

https://github.com/yvesalexandre/bandicoot/blob/73a658f6f17331541cf0b1547028db9b70e8d58a/bandicoot/helper/group.py#L116

**Comment by cynddl** [comment]
Indeed, there should be a _d.month_ field in the tuple. Thanks for noticing that!

**Comment by cynddl** [comment]
Fixed by 3e66b09d4c2b826bfe91e10ed5248565e95e4f8a.
