### ISSUE TITLE
bandicoot/bandicoot/helper/group.py at line 183

### ISSUE THREAD

**Issue by neetip** [computationalprivacy/bandicoot#22]
I found an issue within the - bandicoot/bandicoot/helper/group.py at line 183. That line needed to be commented out for it to work within metrics.all ().

Because with the current code, I get the following error:
RemoteTraceback                           Traceback (most recent call last)

RemoteTraceback: 

"""

Traceback (most recent call last):

  File "/Users/neetipokhriyal/Research/opalalgorithms/src/bandicoot/bandicoot/helper/group.py", line 181, in group_records_with_padding

    pointer = next(_range)

StopIteration

-----------------------

With that line commented out, there is no error. 
Could be a versioning issue too...I use python 3.6. 

Thanks.

**Comment by cynddl** [comment]
Hi @neetip, thanks for the reporting the issue!

1. Can you let me know which version of bandicoot you are using?
2. Can you provide a small reproducible code (+data) that yields the same _StopIteration_ error? We have not received any bug report on the record grouping yet, and the tests run correctly. I'd assume that your data is somehow incorrectly formatted, and the code may have run into an edge case we haven't discovered yet.

Thanks!

**Comment by neetip** [comment]
1. bandicoot Version: 0.5.3

2. I am using the opalalgorithms and the data that comes with it. Here is
my code:


--------------------------

"""Algorithm to aggregate Bandicoot statistics to commune level"""
from __future__ import division, print_function
from opalalgorithms.core import OPALAlgorithm
import json
from bandicoot import utils
import pickle
class SenegalCommuneAggregator(OPALAlgorithm):
    """Calculate population density."""

    def __init__(self):
        """Initialize population density."""
        super(SenegalCommuneAggregator, self).__init__()

    def map(self, params, bandicoot_user):
        """Get home of the bandicoot user.

        Args:
            params (dict): Request parameters.
            bandicoot_user (bandicoot.core.User): Bandicoot user object.

        """
        home = bandicoot_user.recompute_home()
        metrics = utils.all(bandicoot_user)
        metrics_json = json.dumps(metrics)
        if not home:
            return None
        return {getattr(home, params["resolution"]): metrics_json}


---------------------
# create the algorithm object
filename = './aggregator.py'
class_name = 'SenegalCommuneAggregator'
ca_algorithm = dict(
    code=open(filename).read(),
    className=class_name
)
algorunner = AlgorithmRunner(ca_algorithm,dev_mode=True,multiprocess=True,
sandboxing=False)
data_path = '/Users/neetipokhriyal/Research/opalalgorithms/tests/data1'
params = dict(resolution='antenna')
res = algorunner(params,data_path,1)


-------------------------------------------------

**Comment by cynddl** [comment]
Thanks!

@shubhamjain0594 Do you think this could come from _opalalgorithms_ and not _bandicoot_? Do you know of anyone else who reported an issue with _group_records_with_padding_?

Without data to test, it's difficult to understand what's happening.

**Comment by sparachi1011** [comment]
Hi Team, I too got the same issue related to groupby.py  and getting "RuntimeError: generator raised StopIteration" while executing bc.visualization.run(U) module.

![bandicoot error](https://user-images.githubusercontent.com/37170486/76163747-d8cf9100-616e-11ea-99b0-007890ce9946.PNG)

Could any one help in this regard?

**Comment by cynddl** [comment]
Hi @sparachi1011, thanks for the report. Do you have a working example with code and data that you could share so that I can reproduce the issue? Thank you!

**Comment by cynddl** [comment]
Finally fixed in d02ffe819f7efe3ed97c6f9a0cc3d6c97742990f.
