### ISSUE TITLE
bandicoot android app not found

### ISSUE THREAD

**Issue by stiwari2** [computationalprivacy/bandicoot#25]
I was trying to test out data collection by downloading own data using the android app however could not find the app on google playstore. Is the app not available anymore?

[https://play.google.com/store/apps/details?id=edu.mit.media.bandicoot](url)

**Comment by cynddl** [comment]
Hi @stiwari2, unfortunately, Google changed their policy regarding access to SMS/call logs and it's now forbidden to do access the phone metadata We tried to contact them but with no success.

I'm not aware of any other app to extract metadata at the moment.

**Comment by stiwari2** [comment]
Hi @cynddl, in that case, is it possible get the source code of the app which allows building the .apk file?

**Comment by cynddl** [comment]
Hi @stiwari2, you can find it here: https://github.com/yvesalexandre/bandicoot-android-exporter

Might not be up to date with the new Android devtools but PR welcomed to make it Android friendly again!
