### ISSUE TITLE
io.py missing optional_parser function

### ISSUE THREAD

**Issue by obcabanillas** [computationalprivacy/bandicoot#26]
The version of the file 'io.py' that is installed when using pip does not have the function optional_parser. This function (line 190) is in the version of the files available in GitHub.

Not having the optional_parser function makes that some functions on the recharge module do not apply, as the recharge activity only accepts day information but not for a timestamp.

**Comment by cynddl** [comment]
Thanks @obcabanillas, good catch. I thought it was up to date. I have a few fixes to do actually, I'll push a new version to PyPI in the next days.

In the mean time, feel free to install with pip from the master branch.

**Comment by cynddl** [comment]
I just pushed a new version to PyPI. It should be fine now, otherwise please reopen this issue. Thanks again!

**Comment by obcabanillas** [comment]
Thank you!
